# -*- coding: utf-8 -*-
"""Final1.ipynb adlı not defterinin kopyası

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iaZQySm-TZzEVPOD6Yn5YVTb12kTCDRn
"""

!pip install catboost
!pip install catboost imbalanced-learn statsmodels

from google.colab import files
uploaded = files.upload()
import os
print(os.listdir())

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix
from statsmodels.stats.contingency_tables import mcnemar
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from catboost import CatBoostClassifier
from imblearn.over_sampling import SMOTE
from sklearn.feature_selection import RFE
import matplotlib.pyplot as plt
import seaborn as sns

# Veri yükleme ve sütun isimlendirme
df = pd.read_csv("Dataset_spine.csv")
df = df.drop(columns=['Unnamed: 13'])  # boş kolon var ise at
df.rename(columns={
    'Col1': 'pelvic_incidence', 'Col2': 'pelvic_tilt', 'Col3': 'lumbar_lordosis_angle',
    'Col4': 'sacral_slope', 'Col5': 'pelvic_radius', 'Col6': 'degree_spondylolisthesis',
    'Col7': 'horizontal_hips_angle', 'Col8': 'sacrum_angle', 'Col9': 'scoliosis_slope',
    'Col10': 'listesis_grade', 'Col11': 'pelvic_tilt2', 'Col12': 'some_other_feature',
    'Class_att': 'class'
}, inplace=True)

# Sınıf etiketlerini 0 ve 1 yap
df['class'] = df['class'].map({'Normal': 0, 'Abnormal': 1})

X = df.drop('class', axis=1)
y = df['class']

# Veri setini train/test olarak ayır
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standartlaştırma
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Modeller
models = {
    "Yapay Sinir Ağı": MLPClassifier(random_state=42, max_iter=1000),
    "CART": DecisionTreeClassifier(random_state=42),
    "CatBoost": CatBoostClassifier(verbose=0, random_state=42)
}

# McNemar testi için yardımcı fonksiyon
def mcnemar_test(y_true, pred1, pred2):
    table = confusion_matrix(pred1 == y_true, pred2 == y_true)
    result = mcnemar(table, exact=False)
    return result.pvalue

# Deneyleri çalıştıracak fonksiyon
def run_experiment(X_train, y_train, X_test, y_test, experiment_name):
    print(f"\n {experiment_name} Doğruluk ve Karışıklık Matrisi Sonuçları:")
    results = {}
    preds = {}
    conf_matrices = {}

    for name, model in models.items():
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        acc = accuracy_score(y_test, y_pred)
        results[name] = acc
        preds[name] = y_pred
        conf_matrices[name] = confusion_matrix(y_test, y_pred)
        print(f"{name} doğruluk: {acc:.4f}")
        print(f"{name} Karışıklık Matrisi:\n{conf_matrices[name]}\n")

    # McNemar testleri
    pairs = [("Yapay Sinir Ağı", "CART"), ("Yapay Sinir Ağı", "CatBoost"), ("CART", "CatBoost")]
    print(f" {experiment_name} McNemar Test Sonuçları:")
    for m1, m2 in pairs:
        p = mcnemar_test(y_test, preds[m1], preds[m2])
        anlamlı_mi = "Evet" if p < 0.05 else "Hayır"
        print(f"{m1} vs {m2}: p-değeri = {p:.4f} - Anlamlı mı? {anlamlı_mi}")

    return results, conf_matrices

# Deney 1: Ham Veri
results1, conf_matrices1 = run_experiment(X_train_scaled, y_train, X_test_scaled, y_test, "Deney 1 (Ham Veri)")

# Deney 2: SMOTE + RFE
smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X_train_scaled, y_train)
rfe = RFE(DecisionTreeClassifier(random_state=42), n_features_to_select=5)
X_rfe = rfe.fit_transform(X_resampled, y_resampled)
X_test_rfe = rfe.transform(X_test_scaled)
results2, conf_matrices2 = run_experiment(X_rfe, y_resampled, X_test_rfe, y_test, "Deney 2 (SMOTE + RFE)")

# Deney 3: RFE + SMOTE
rfe2 = RFE(DecisionTreeClassifier(random_state=42), n_features_to_select=5)
X_train_rfe = rfe2.fit_transform(X_train_scaled, y_train)
X_test_rfe2 = rfe2.transform(X_test_scaled)
X_resampled2, y_resampled2 = smote.fit_resample(X_train_rfe, y_train)
results3, conf_matrices3 = run_experiment(X_resampled2, y_resampled2, X_test_rfe2, y_test, "Deney 3 (RFE + SMOTE)")

# Sonuçları tablo halinde yazdırma
df_results = pd.DataFrame({
    "Deney 1": results1,
    "Deney 2": results2,
    "Deney 3": results3
}).T

print("\n Modellerin Deneylere Göre Doğruluk Tablosu:")
print(df_results)

# Grafik: Doğrulukların karşılaştırması
df_results.plot(kind='bar', figsize=(10,6))
plt.title("Modellerin Deneylere Göre Doğruluk Karşılaştırması")
plt.ylabel("Doğruluk")
plt.xlabel("Deneyler")
plt.ylim(0.6, 1)
plt.xticks(rotation=0)
plt.legend(title="Modeller")
plt.grid(axis='y')
plt.show()

# Karışıklık matrislerini çizdiren fonksiyon
def plot_confusion_matrices_side_by_side(conf_matrices, title):
    n_models = len(conf_matrices)
    plt.figure(figsize=(5 * n_models, 4))

    for i, (model_name, matrix) in enumerate(conf_matrices.items()):
        plt.subplot(1, n_models, i + 1)
        sns.heatmap(matrix, annot=True, fmt='d', cmap='Blues', cbar=False)
        plt.title(f"{title} - {model_name}")
        plt.xlabel("Tahmin")
        plt.ylabel("Gerçek")

    plt.tight_layout()
    plt.show()

# Tüm deneyler için:
plot_confusion_matrices_side_by_side(conf_matrices1, "Deney 1 (Ham Veri)")
plot_confusion_matrices_side_by_side(conf_matrices2, "Deney 2 (SMOTE + RFE)")
plot_confusion_matrices_side_by_side(conf_matrices3, "Deney 3 (RFE + SMOTE)")
